export const TYPES = {
  ADDTOCART: 'ADDTOCART',
  DELETEFROMCART: 'DELETEFROMCART',
  CHANGECATEGORY: 'CHANGECATEGORY',
  SETINFO: 'SETINFO',
  SETUSER: 'SETUSER',
  SETCART: 'SETCART',
  SETTOKEN: 'SETTOKEN',
  LOGOUT: 'LOGOUT'
}
